Registration Type
canvas-gamification/canvas-gamification pull request #265
Opened 2021-11-13 20:03 UTC by carson-ricca

2021-11-15 18:42 UTC, carson-ricca commented
- One odd thing I'm having trouble figuring out is if I change the `registration_type` in the admin portal, `is_verified` gets set to false. Not sure how this is happening.
- Other questions do we want to set the registration type automatically? It is currently set to STUDENT by default but there may be a way to get the correct type automatically everytime?

2021-11-16 23:07 UTC, keyvankhademi requested changes

2021-11-16 23:07 UTC, keyvankhademi commented on canvas/models.py
> +        return course_reg == INSTRUCTOR
shouldn't this be course_reg.registration_type == INSTRUCTOR?

2021-11-16 23:14 UTC, keyvankhademi approved these changes

2021-11-16 23:14 UTC, merged