Display students only on challenge leaderboard
canvas-gamification/canvas-gamification pull request #362
Opened 2023-03-14 21:23 UTC by yuqi88

closes #361

2023-03-14 23:14 UTC, yuqi88 commented
Do we want to display only students and exclude only Admins, teachers and TAs?

2023-03-21 21:14 UTC, keyvankhademi requested changes

2023-03-21 21:14 UTC, keyvankhademi commented on api/views/course.py
> +            .all()
```suggestion
            for course_reg in course.canvascourseregistration_set.filter(status="VERIFIED", registration_type="STUDENT")
            .all()
```

2023-03-21 21:14 UTC, keyvankhademi commented on api/views/event.py
> +            if team.course_registrations.all().filter(status="VERIFIED", registration_type="STUDENT").all()
Did you mean this?
```suggestion
            if team.course_registrations.filter(status="VERIFIED", registration_type="STUDENT").exist()
```

2023-03-21 22:23 UTC, keyvankhademi approved these changes

2023-03-21 22:23 UTC, merged